import { Scenario } from '../types';

export const DEMO_SCENARIO: Scenario = {
  id: 'demo_scenario',
  name: 'Demo Scenario',
  description: 'Standard baseline river-basin model with 1 Reservoir, 2 Canal Networks, and 3 Crop Zones experiencing 15% deficit.',
  reservoir: {
    name: 'Bhakra-Cauvery Primary Reservoir',
    availableWater: 1000,
    minReserve: 100,
  },
  canals: [
    {
      id: 'canal_a',
      name: 'Canal A (North Branch)',
      maxCapacity: 600,
      minFlow: 50,
      currentFlow: 580,
      efficiency: 0.94,
    },
    {
      id: 'canal_b',
      name: 'Canal B (South Branch)',
      maxCapacity: 400,
      minFlow: 30,
      currentFlow: 390,
      efficiency: 0.92,
    },
  ],
  crops: [
    {
      id: 'paddy',
      name: 'Paddy (Basmati)',
      demand: 420,
      minAllocation: 250,
      maxAllocation: 450,
      priority: 1.25,
      canalId: 'canal_a',
      iconType: 'paddy',
      economicYieldPerUnit: 3.5,
    },
    {
      id: 'cotton',
      name: 'Cotton (Long Staple)',
      demand: 350,
      minAllocation: 180,
      maxAllocation: 380,
      priority: 1.0,
      canalId: 'canal_b',
      iconType: 'cotton',
      economicYieldPerUnit: 2.8,
    },
    {
      id: 'pulses',
      name: 'Pulses (Chickpea/Lentil)',
      demand: 230,
      minAllocation: 100,
      maxAllocation: 250,
      priority: 0.85,
      canalId: 'canal_b',
      iconType: 'pulses',
      economicYieldPerUnit: 2.1,
    },
  ],
  penalties: {
    reservoirLimitPenalty: 4.5,
    canalCapacityPenalty: 3.8,
    shortfallPenalty: 2.0,
  },
};

export const SEVERE_DROUGHT_SCENARIO: Scenario = {
  id: 'severe_drought',
  name: 'Severe Drought Emergency',
  description: 'Reservoir inflow reduced by 40%. Severe water scarcity requiring critical crop preservation.',
  reservoir: {
    name: 'Bhakra-Cauvery Primary Reservoir',
    availableWater: 600,
    minReserve: 120,
  },
  canals: [
    {
      id: 'canal_a',
      name: 'Canal A (North Branch)',
      maxCapacity: 450,
      minFlow: 40,
      currentFlow: 350,
      efficiency: 0.88,
    },
    {
      id: 'canal_b',
      name: 'Canal B (South Branch)',
      maxCapacity: 300,
      minFlow: 20,
      currentFlow: 230,
      efficiency: 0.86,
    },
  ],
  crops: [
    {
      id: 'paddy',
      name: 'Paddy (Basmati)',
      demand: 400,
      minAllocation: 200,
      maxAllocation: 400,
      priority: 1.35,
      canalId: 'canal_a',
      iconType: 'paddy',
      economicYieldPerUnit: 3.5,
    },
    {
      id: 'cotton',
      name: 'Cotton (Long Staple)',
      demand: 320,
      minAllocation: 140,
      maxAllocation: 300,
      priority: 0.9,
      canalId: 'canal_b',
      iconType: 'cotton',
      economicYieldPerUnit: 2.8,
    },
    {
      id: 'pulses',
      name: 'Pulses (Chickpea/Lentil)',
      demand: 220,
      minAllocation: 80,
      maxAllocation: 200,
      priority: 0.75,
      canalId: 'canal_b',
      iconType: 'pulses',
      economicYieldPerUnit: 2.1,
    },
  ],
  penalties: {
    reservoirLimitPenalty: 6.0,
    canalCapacityPenalty: 4.5,
    shortfallPenalty: 2.8,
  },
};

export const MONSOON_ABUNDANCE_SCENARIO: Scenario = {
  id: 'monsoon_abundance',
  name: 'Monsoon Surfeit & Storage',
  description: 'Reservoir full at 1,400 units. Canal transport bottlenecks become the primary limiting constraint.',
  reservoir: {
    name: 'Bhakra-Cauvery Primary Reservoir',
    availableWater: 1400,
    minReserve: 150,
  },
  canals: [
    {
      id: 'canal_a',
      name: 'Canal A (North Branch)',
      maxCapacity: 650,
      minFlow: 60,
      efficiency: 0.95,
    },
    {
      id: 'canal_b',
      name: 'Canal B (South Branch)',
      maxCapacity: 450,
      minFlow: 40,
      efficiency: 0.93,
    },
  ],
  crops: [
    {
      id: 'paddy',
      name: 'Paddy (Basmati)',
      demand: 520,
      minAllocation: 300,
      maxAllocation: 550,
      priority: 1.2,
      canalId: 'canal_a',
      iconType: 'paddy',
      economicYieldPerUnit: 3.5,
    },
    {
      id: 'cotton',
      name: 'Cotton (Long Staple)',
      demand: 400,
      minAllocation: 220,
      maxAllocation: 420,
      priority: 1.05,
      canalId: 'canal_b',
      iconType: 'cotton',
      economicYieldPerUnit: 2.8,
    },
    {
      id: 'pulses',
      name: 'Pulses (Chickpea/Lentil)',
      demand: 260,
      minAllocation: 120,
      maxAllocation: 280,
      priority: 0.85,
      canalId: 'canal_b',
      iconType: 'pulses',
      economicYieldPerUnit: 2.1,
    },
  ],
  penalties: {
    reservoirLimitPenalty: 3.5,
    canalCapacityPenalty: 5.0,
    shortfallPenalty: 1.5,
  },
};

export const CANAL_BREACH_SCENARIO: Scenario = {
  id: 'canal_breach',
  name: 'Canal B Structural Failure',
  description: 'Canal B breached due to silt pressure; capacity reduced from 400 to 180 units. Rerouting required.',
  reservoir: {
    name: 'Bhakra-Cauvery Primary Reservoir',
    availableWater: 1000,
    minReserve: 100,
  },
  canals: [
    {
      id: 'canal_a',
      name: 'Canal A (North Branch)',
      maxCapacity: 600,
      minFlow: 50,
      efficiency: 0.94,
    },
    {
      id: 'canal_b',
      name: 'Canal B (South Branch - Breached)',
      maxCapacity: 180,
      minFlow: 20,
      efficiency: 0.72,
    },
  ],
  crops: [
    {
      id: 'paddy',
      name: 'Paddy (Basmati)',
      demand: 420,
      minAllocation: 250,
      maxAllocation: 450,
      priority: 1.2,
      canalId: 'canal_a',
      iconType: 'paddy',
      economicYieldPerUnit: 3.5,
    },
    {
      id: 'cotton',
      name: 'Cotton (Long Staple)',
      demand: 350,
      minAllocation: 100,
      maxAllocation: 220,
      priority: 1.0,
      canalId: 'canal_b',
      iconType: 'cotton',
      economicYieldPerUnit: 2.8,
    },
    {
      id: 'pulses',
      name: 'Pulses (Chickpea/Lentil)',
      demand: 230,
      minAllocation: 60,
      maxAllocation: 140,
      priority: 0.8,
      canalId: 'canal_b',
      iconType: 'pulses',
      economicYieldPerUnit: 2.1,
    },
  ],
  penalties: {
    reservoirLimitPenalty: 4.5,
    canalCapacityPenalty: 7.0,
    shortfallPenalty: 2.0,
  },
};

export const ALL_PRESETS: Scenario[] = [
  DEMO_SCENARIO,
  SEVERE_DROUGHT_SCENARIO,
  MONSOON_ABUNDANCE_SCENARIO,
  CANAL_BREACH_SCENARIO,
];
